trainer:
  data:
    path: classpath:data/trainers.json
trainee:
  data:
    path: classpath:data/trainees.json
training:
  data:
    path: classpath:data/trainings.json

jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:testdb
  user: ${DB_USER:sa}
  pass: ${DB_PASS:password}

hibernate:
  hbm2ddl.auto: create-drop
  dialect: org.hibernate.dialect.H2Dialect